Heritage Skills SA, an NPO that conducts field-training programs across South Africa (e.g., Gauteng, Western Cape, KwaZulu-Natal) to train community members, research assistants, and municipal workers in archeological site documentation, spatial mapping (GIS), and heritage database cataloguing.

The Problem: The training coordinators record attendance, assessment scores, equipment allocations, and participant feedback using manual spreadsheets. The raw dataset contains severe human errors: inconsistent text casing, mixed date formats, missing IDs, duplicate rows, and bad numerical ranges.

In [6]:
# load and view data
import pandas as pd
heritage = pd.read_csv('dirty_npo_training_data.csv - raw_data.csv', index_col=0)
heritage.head()

                          Full_Name  ... Funding_Sponsor
Participant_ID                       ...
EMP-001            Sibusiso Dlamini  ...     SAHRA_Grant
EMP-002         SARAH VAN DER MERWE  ...     SAHRA_Grant
EMP-003               Thabo Mokoena  ...       DSAC_Fund
EMP-004             Lindiwe Khumalo  ...       DSAC_Fund
EMP-005            sibusiso dlamini  ...     SAHRA_Grant

[5 rows x 11 columns]

In [7]:
import numpy as np
import pandas as pd

# 1. Standardize Text Casing
heritage['Full_Name'] = heritage['Full_Name'].astype(str).str.title().str.strip()

# 2. Standardize Province Codes
province_map = {'Gauteng': 'GP',
                'Western Cape': 'WC', 
                'GP': 'GP', 
                'WC': 'WC', 
                'KZN': 'KZN'}
heritage['Province_Code'] = heritage['Province_Code'].map(province_map)

# 3. Clean Equipment Returned Status
heritage['Equipment_Returned'] = heritage['Equipment_Returned'].astype(str).str.capitalize().replace(
    {'Yes': 'Returned',
     'No': 'Unreturned',
     'Missing': 'Unreturned'})

# 4. Clean Numeric Percentage Scores
heritage['Attendance_Pct'] = heritage['Attendance_Pct'].astype(str).str.rstrip('%')
heritage['Attendance_Pct'] = pd.to_numeric(heritage['Attendance_Pct'], errors='coerce')
heritage['Attendance_Pct'] = heritage['Attendance_Pct'].apply(lambda x: np.nan if (x > 100 or x < 0) else x)

# 5. Clean Test Scores
heritage['Pre_Test_Score'] = pd.to_numeric(heritage['Pre_Test_Score'], errors='coerce')
heritage['Post_Test_Score'] = pd.to_numeric(heritage['Post_Test_Score'], errors='coerce')

# Cap scores between 0 and 100
heritage['Post_Test_Score'] = heritage['Post_Test_Score'].clip(lower=0, upper=100)

# 6. Remove Duplicates
heritage = heritage.drop_duplicates(subset=['Full_Name', 'Start_Date'], keep='first')

# Output cleaned dataset
heritage.to_csv('cleaned_npo_training_data.csv', index=False)
heritage.head(10)

                          Full_Name  ... Funding_Sponsor
Participant_ID                       ...
EMP-001            Sibusiso Dlamini  ...     SAHRA_Grant
EMP-002         Sarah Van Der Merwe  ...     SAHRA_Grant
EMP-003               Thabo Mokoena  ...       DSAC_Fund
EMP-004             Lindiwe Khumalo  ...       DSAC_Fund
EMP-006                 Johan Botha  ...   Private_Donor
EMP-007             Nokuthula Zungu  ...       DSAC_Fund
EMP-008               Kagiso Lesedi  ...     SAHRA_Grant
EMP-009                Pieter Naude  ...   Private_Donor
EMP-010              Nomvula Ndlovu  ...       DSAC_Fund
EMP-011             Anelisa Sithole  ...     SAHRA_Grant

[10 rows x 11 columns]